# This is the main configuration file for Netlify

[build]
  # This tells Netlify where our serverless functions are located.
  functions = "netlify/functions/"

[[redirects]]
  # This is a rewrite rule for your API function.
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# --- Custom 404 Page Rule (ADD THIS PART) ---
# This rule tells Netlify to show your custom 404.html page
# whenever a user tries to visit a page that doesn't exist.
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404